### ISSUE TITLE
请大佬加群，国科大集体电台BI1GK

### ISSUE THREAD

**Issue by StrideZhou** [tomzbj/diy#1]
BI1GK
724482439

**Comment by tomzbj** [comment]
是微信群吗? 搜不到啊

Hao Zhang
86-10-82543700
1-335, Technical Institute of Physics and Chemistry
29  Zhongguancun East Road
Haidian District, Beijing, 100190, P. R. China


stride ***@***.***> 于2022年3月22日周二 00:30写道：

**Comment by StrideZhou** [comment]
QQ群哦

**Comment by tomzbj** [comment]
不好意思, 很久不用QQ了...

Hao Zhang
86-10-82543700
1-335, Technical Institute of Physics and Chemistry
29  Zhongguancun East Road
Haidian District, Beijing, 100190, P. R. China


stride ***@***.***> 于2022年6月30日周四 15:53写道：
